### ISSUE TITLE
sajson on hackage does not contain sajson_wrapper.h

### ISSUE THREAD

**Issue by mwotton** [capital-match/haskell-sajson#1]
therefore can't build. works fine building from source.

**Comment by kccqzy** [comment]
Okay. I don't actually use this library any more. Feel free to submit to a PR! 

Shouldn't be too hard I guess; just adding the file (maybe also the `hpp` file) to the cabal file?

**Comment by peterbecich** [comment]
I believe this (https://github.com/kccqzy/haskell-sajson/pull/3) solves it

**Comment by kccqzy** [comment]
Just uploaded a new version so that it at least builds: https://hackage.haskell.org/package/sajson-0.2.0.0

Sorry for the late reply. This project is, as you might've surmised, not being maintained.
